//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workWithBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Halls> Halls { get; set; }
        public virtual DbSet<Kinoteatr> Kinoteatr { get; set; }
        public virtual DbSet<Role_user> Role_user { get; set; }
        public virtual DbSet<sales> sales { get; set; }
        public virtual DbSet<sessions_days> sessions_days { get; set; }
        public virtual DbSet<sessions_time> sessions_time { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<type_halls> type_halls { get; set; }
        public virtual DbSet<type_tickets> type_tickets { get; set; }
        public virtual DbSet<userphoto> userphoto { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
