//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workWithBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kinoteatr
    {
        public int id_kinoteatr { get; set; }
        public string kinoteatr1 { get; set; }
        public int count_halls { get; set; }
    }
}
