//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workWithBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        public int id_sales { get; set; }
        public int id_tickets { get; set; }
        public int id_halls { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
    
        public virtual Halls Halls { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
