//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workWithBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        public int id_sales { get; set; }
        public int id_tickets { get; set; }
        public int id_halls { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
    
        public virtual Halls Halls { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
