//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workWithBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
           this.sales = new HashSet<sales>();
        }


        public int id_ticket { get; set; }
        public string session { get; set; }
        public int id_session_time { get; set; }
        public int id_session_day { get; set; }
        public int id_halls { get; set; }
        public int id_type_tickets { get; set; }
        public Nullable<int> price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales> sales { get; set; }
 
        public virtual sessions_days sessions_days { get; set; }
        public virtual sessions_time sessions_time { get; set; }
        public virtual type_tickets type_tickets { get; set; }
    }
}
