//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workWithBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id_user { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string lastname { get; set; }
        public string login { get; set; }
        public int password { get; set; }
        public System.DateTime birthday { get; set; }
        public int id_gender { get; set; }
        public int id_role { get; set; }
    
        public virtual Genders Genders { get; set; }
        public virtual Role_user Role_user { get; set; }
    }
}
