//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workWithBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class userphoto
    {
        public int id_photo { get; set; }
        public int id_user { get; set; }
        public byte[] photo_binary { get; set; }
        public string photo_path { get; set; }
    
        public virtual users users { get; set; }
    }
}
